### ISSUE TITLE
Vendor libraries

### ISSUE THREAD

**Issue by kingsleyzissou** [maybeweare/breakpoint.css#17]
I think we should possibly look at including Normalize.css.
Reset.css is too aggressive as it resets everything and will take away some basic styling that we will never build back into the framework.

Normalize would just make everything consistent across all the browsers so we can just build on that.
Essentially just removing custom browser styling - it's only about 5kb unminified.
https://github.com/necolas/normalize.css/blob/master/normalize.css

**Comment by kingsleyzissou** [comment]
@dimitraz @piccolazucca

**Comment by dimitraz** [comment]
Closing for now as we have `minireset`, we can always reopen this at a later stage
